<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="HOMING" Id="{8a884f8c-3637-4562-9e0d-7245c4963ef4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION HOMING : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="HOMING">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>